apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: f98e273e-0592-4f6f-9a23-5e5903dec480
    subject: disk-fill_litmus
    workflow_id: 18e076b3-3ca1-4ff9-a211-5d3af2a70ca5
    workflows.argoproj.io/controller-instanceid: f98e273e-0592-4f6f-9a23-5e5903dec480
  name: disk-fill-1650311693
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: disk-fill
        template: disk-fill
  - container:
      args:
      - kubectl apply -f /tmp/disk-fill.yaml -n {{workflow.parameters.adminModeNamespace}}
        |  sleep 30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:2.7.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: disk-fill
        path: /tmp/disk-fill.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Fillup Ephemeral Storage of a Resource
            kind: ChaosExperiment
            metadata:
              name: disk-fill
              labels:
                name: disk-fill
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: 2.7.0
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - apps
                    resources:
                      - deployments
                      - statefulsets
                      - replicasets
                      - daemonsets
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - apps.openshift.io
                    resources:
                      - deploymentconfigs
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - ""
                    resources:
                      - replicationcontrollers
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - rollouts
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: litmuschaos/go-runner:2.7.0
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name disk-fill
                command:
                  - /bin/bash
                env:
                  - name: TARGET_CONTAINER
                    value: ""
                  - name: FILL_PERCENTAGE
                    value: "80"
                  - name: TOTAL_CHAOS_DURATION
                    value: "60"
                  - name: RAMP_TIME
                    value: ""
                  - name: LIB
                    value: litmus
                  - name: DATA_BLOCK_SIZE
                    value: "256"
                  - name: TARGET_PODS
                    value: ""
                  - name: EPHEMERAL_STORAGE_MEBIBYTES
                    value: ""
                  - name: PODS_AFFECTED_PERC
                    value: ""
                  - name: LIB_IMAGE
                    value: litmuschaos/go-runner:2.7.0
                  - name: CONTAINER_PATH
                    value: /var/lib/docker/containers
                  - name: SEQUENCE
                    value: parallel
                labels:
                  name: disk-fill
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/host-path-usage: "true"
                  app.kubernetes.io/version: 2.7.0
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-disk-fill.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:2.7.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: disk-fill
        path: /tmp/chaosengine-disk-fill.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: disk-fill
              labels:
                instance_id: b6d32f06-2b60-4715-b7ac-a0af6431747c
                context: disk-fill_litmus
                workflow_name: disk-fill-1650311693
            spec:
              engineState: active
              auxiliaryAppInfo: ""
              appinfo:
                appns: test
                applabel: app=nginx
                appkind: deployment
              chaosServiceAccount: litmus-admin
              experiments:
                - name: disk-fill
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "60"
                        - name: FILL_PERCENTAGE
                          value: "100"
                        - name: PODS_AFFECTED_PERC
                          value: ""
                        - name: CONTAINER_PATH
                          value: /var/lib/docker/containers
                    probe: []
              annotationCheck: "false"
    metadata:
      labels:
        weight: "10"
    name: disk-fill
    outputs: {}
status:
  finishedAt: null
  startedAt: null
