apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: f3e3ffd8-4f1b-4eda-857a-368a0ddd2d26
    subject: free-form-with-sa_litmus
    workflow_id: fdd8cde2-4d52-46ef-8ad7-52cc99d3d5df
    workflows.argoproj.io/controller-instanceid: f3e3ffd8-4f1b-4eda-857a-368a0ddd2d26
  name: free-form-with-sa
  namespace: litmus
spec:
  arguments: {}
  entrypoint: diamond
  serviceAccountName: argo-chaos
  templates:
  - container:
      command:
      - echo
      - '{{inputs.parameters.message}}'
      image: alpine:3.7
      name: ""
      resources: {}
    inputs:
      parameters:
      - name: message
    metadata: {}
    name: echo
    outputs: {}
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: message
            value: A
        name: A
        template: nested-diamond
      - arguments:
          parameters:
          - name: message
            value: B
        depends: A
        name: B
        template: nested-diamond
      - arguments:
          parameters:
          - name: message
            value: C
        depends: A
        name: C
        template: nested-diamond
      - arguments:
          parameters:
          - name: message
            value: D
        depends: B && C
        name: D
        template: nested-diamond
    inputs: {}
    metadata: {}
    name: diamond
    outputs: {}
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: message
            value: '{{inputs.parameters.message}}A'
        name: A
        template: echo
      - arguments:
          parameters:
          - name: message
            value: '{{inputs.parameters.message}}B'
        depends: A
        name: B
        template: echo
      - arguments:
          parameters:
          - name: message
            value: '{{inputs.parameters.message}}C'
        depends: A
        name: C
        template: echo
      - arguments:
          parameters:
          - name: message
            value: '{{inputs.parameters.message}}D'
        depends: B && C
        name: D
        template: echo
    inputs:
      parameters:
      - name: message
    metadata: {}
    name: nested-diamond
    outputs: {}
status:
  finishedAt: null
  startedAt: null
