apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 2777edec-0224-499c-a835-bf93bbdf9413
    subject: no-tunable-pod-autoscaler_litmus
    workflow_id: 4360f454-8340-45c0-9c37-774c53c2255f
    workflows.argoproj.io/controller-instanceid: 2777edec-0224-499c-a835-bf93bbdf9413
  name: no-tunable-pod-autoscaler-1649940654
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: pod-autoscaler
        template: pod-autoscaler
    - - arguments: {}
        name: revert-chaos
        template: revert-chaos
  - container:
      args:
      - kubectl apply -f /tmp/pod-autoscaler.yaml -n {{workflow.parameters.adminModeNamespace}}
        |  sleep 30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:2.7.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-autoscaler
        path: /tmp/pod-autoscaler.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Scale the application replicas and test the node autoscaling on cluster
            kind: ChaosExperiment
            metadata:
              name: pod-autoscaler
              labels:
                name: pod-autoscaler
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: 2.7.0
            spec:
              definition:
                scope: Cluster
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - apps
                    resources:
                      - deployments
                      - statefulsets
                    verbs:
                      - list
                      - get
                      - patch
                      - update
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: litmuschaos/go-runner:2.7.0
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name pod-autoscaler
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "60"
                  - name: RAMP_TIME
                    value: ""
                  - name: REPLICA_COUNT
                    value: "5"
                  - name: LIB
                    value: litmus
                labels:
                  name: pod-autoscaler
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: 2.7.0
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-pod-autoscaler.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:2.7.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-autoscaler
        path: /tmp/chaosengine-pod-autoscaler.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: pod-autoscaler
              labels:
                instance_id: 7feac580-4394-4b40-bc98-21aafeaf4b2d
                context: pod-autoscaler_litmus
                workflow_name: no-tunable-pod-autoscaler-1649940654
            spec:
              engineState: active
              auxiliaryAppInfo: ""
              appinfo:
                appns: demo
                applabel: app=convertigo
                appkind: deployment
              chaosServiceAccount: litmus-admin
              experiments:
                - name: pod-autoscaler
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: ""
                        - name: REPLICA_COUNT
                          value: ""
                    probe: []
              annotationCheck: "false"
    metadata:
      labels:
        weight: "10"
    name: pod-autoscaler
    outputs: {}
  - container:
      args:
      - 'kubectl delete chaosengine -l ''instance_id in (7feac580-4394-4b40-bc98-21aafeaf4b2d,
        )'' -n {{workflow.parameters.adminModeNamespace}} '
      command:
      - sh
      - -c
      image: litmuschaos/k8s:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: revert-chaos
    outputs: {}
status:
  finishedAt: null
  startedAt: null
