apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 15fc4ecc-d759-45b8-8754-6621aa68f868
    subject: node-io-stress-negative-affec-perc_agent
    workflow_id: c9751855-0a03-4834-8917-9e82dba8b343
    workflows.argoproj.io/controller-instanceid: 15fc4ecc-d759-45b8-8754-6621aa68f868
  name: node-io-stress-negative-affec-perc-1650304088
  namespace: agent
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: agent
  entrypoint: custom-chaos
  nodeSelector:
    kubernetes.io/hostname: gke-hce-testing-cluster-pool-1-15a8d68e-hrbq
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: node-io-stress
        template: node-io-stress
  - container:
      args:
      - kubectl apply -f /tmp/node-io-stress.yaml -n {{workflow.parameters.adminModeNamespace}}
        |  sleep 30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:2.7.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: node-io-stress
        path: /tmp/node-io-stress.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Give IO disk stress on a node belonging to a deployment
            kind: ChaosExperiment
            metadata:
              name: node-io-stress
              labels:
                name: node-io-stress
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: 2.8.0
            spec:
              definition:
                scope: Cluster
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                  - apiGroups:
                      - ""
                    resources:
                      - nodes
                    verbs:
                      - get
                      - list
                image: litmuschaos/go-runner:2.8.0
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name node-io-stress
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "120"
                  - name: FILESYSTEM_UTILIZATION_PERCENTAGE
                    value: "10"
                  - name: FILESYSTEM_UTILIZATION_BYTES
                    value: ""
                  - name: CPU
                    value: "1"
                  - name: NUMBER_OF_WORKERS
                    value: "4"
                  - name: VM_WORKERS
                    value: "1"
                  - name: TARGET_NODES
                    value: ""
                  - name: NODE_LABEL
                    value: ""
                  - name: RAMP_TIME
                    value: ""
                  - name: LIB
                    value: litmus
                  - name: LIB_IMAGE
                    value: litmuschaos/go-runner:2.8.0
                  - name: NODES_AFFECTED_PERC
                    value: ""
                  - name: SEQUENCE
                    value: parallel
                labels:
                  name: node-io-stress
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: 2.8.0
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-node-io-stress.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:2.7.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: node-io-stress
        path: /tmp/chaosengine-node-io-stress.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: node-io-stress
              labels:
                instance_id: 1cab6815-8b8e-4edb-b262-7714f5fc1cc5
                context: node-io-stress_agent
                workflow_name: node-io-stress-negative-affec-perc-1650304088
            spec:
              engineState: active
              auxiliaryAppInfo: ""
              chaosServiceAccount: litmus-admin
              experiments:
                - name: node-io-stress
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "60"
                        - name: FILESYSTEM_UTILIZATION_PERCENTAGE
                          value: "10"
                        - name: CPU
                          value: "1"
                        - name: NUMBER_OF_WORKERS
                          value: "4"
                        - name: NODES_AFFECTED_PERC
                          value: "-100"
                        - name: TARGET_NODES
                          value: gke-hce-testing-cluster-pool-1-15a8d68e-p1kg,gke-hce-testing-cluster-pool-1-15a8d68e-rcrs
                        - name: FILESYSTEM_UTILIZATION_BYTES
                          value: "0"
                    probe: []
              annotationCheck: "false"
    metadata:
      labels:
        weight: "10"
    name: node-io-stress
    outputs: {}
status:
  finishedAt: null
  startedAt: null
