apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 15fc4ecc-d759-45b8-8754-6621aa68f868
    subject: pod-network-partition_agent
    workflow_id: 032f41b6-f1c8-4e8f-8d40-dbb4d5a5fd2a
    workflows.argoproj.io/controller-instanceid: 15fc4ecc-d759-45b8-8754-6621aa68f868
  name: pod-network-partition-1650457990
  namespace: agent
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: agent
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: pod-network-partition
        template: pod-network-partition
  - container:
      args:
      - kubectl apply -f /tmp/pod-network-partition.yaml -n {{workflow.parameters.adminModeNamespace}}
        |  sleep 30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:2.7.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-network-partition
        path: /tmp/pod-network-partition.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Injects 100% network packet loss on pods belonging to an app deployment
            kind: ChaosExperiment
            metadata:
              name: pod-network-partition
              labels:
                name: pod-network-partition
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: 2.8.0
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - networking.k8s.io
                    resources:
                      - networkpolicies
                    verbs:
                      - create
                      - delete
                      - list
                      - get
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: litmuschaos/go-runner:2.8.0
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name pod-network-partition
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "60"
                  - name: RAMP_TIME
                    value: ""
                  - name: LIB
                    value: litmus
                  - name: DESTINATION_IPS
                    value: ""
                  - name: DESTINATION_HOSTS
                    value: ""
                  - name: POLICY_TYPES
                    value: all
                  - name: POD_SELECTOR
                    value: ""
                  - name: NAMESPACE_SELECTOR
                    value: ""
                  - name: PORTS
                    value: ""
                labels:
                  name: pod-network-partition
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: 2.8.0
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-pod-network-partition.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:2.7.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-network-partition
        path: /tmp/chaosengine-pod-network-partition.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: pod-network-partition
              labels:
                instance_id: 141c8631-7d3c-4324-b67f-6a7f5e1ba4df
                context: pod-network-partition_agent
                workflow_name: pod-network-partition-1650457990
            spec:
              engineState: active
              appinfo:
                appns: nginx
                applabel: app=nginx
                appkind: deployment
              chaosServiceAccount: litmus-admin
              experiments:
                - name: pod-network-partition
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "60"
                        - name: DESTINATION_HOSTS
                          value: google.com
                        - name: DESTINATION_IPS
                          value: 8.8.8.8.
                        - name: NAMESPACE_SELECTOR
                          value: kubernetes.io/metadata.name=nginx
                        - name: POD_SELECTOR
                          value: app=nginx
                        - name: POLICY_TYPES
                          value: all
                        - name: PORTS
                          value: ""
                    probe: []
              annotationCheck: "false"
    metadata:
      labels:
        weight: "10"
    name: pod-network-partition
    outputs: {}
status:
  finishedAt: null
  startedAt: null
