apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 4393ea8b-11ac-407f-808f-4421baf0d9dc
    subject: pod-cpu-hog-exec-28a_sj
    workflow_id: 61d07719-72c6-43a2-84a9-3e29dfb8a73d
    workflows.argoproj.io/controller-instanceid: 4393ea8b-11ac-407f-808f-4421baf0d9dc
  name: pod-cpu-hog-exec-28a-1650197201
  namespace: sj
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: sj
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: pod-cpu-hog-exec
        template: pod-cpu-hog-exec
  - container:
      args:
      - kubectl apply -f /tmp/pod-cpu-hog-exec.yaml -n {{workflow.parameters.adminModeNamespace}}
        |  sleep 30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:2.7.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-cpu-hog-exec
        path: /tmp/pod-cpu-hog-exec.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Injects cpu consumption on pods belonging to an app deployment
            kind: ChaosExperiment
            metadata:
              name: pod-cpu-hog-exec
              labels:
                name: pod-cpu-hog-exec
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: 2.7.0
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - apps
                    resources:
                      - deployments
                      - statefulsets
                      - replicasets
                      - daemonsets
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - apps.openshift.io
                    resources:
                      - deploymentconfigs
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - ""
                    resources:
                      - replicationcontrollers
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - rollouts
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: litmuschaos/go-runner:2.7.0
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name pod-cpu-hog-exec
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "60"
                  - name: CPU_CORES
                    value: "1"
                  - name: PODS_AFFECTED_PERC
                    value: ""
                  - name: RAMP_TIME
                    value: ""
                  - name: LIB
                    value: litmus
                  - name: CHAOS_KILL_COMMAND
                    value: kill $(find /proc -name exe -lname '*/md5sum' 2>&1 | grep -v 'Permission
                      denied' | awk -F/ '{print $(NF-1)}')
                  - name: TARGET_PODS
                    value: ""
                  - name: SEQUENCE
                    value: parallel
                labels:
                  name: pod-cpu-hog-exec
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: 2.7.0
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-pod-cpu-hog-exec.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:2.7.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-cpu-hog-exec
        path: /tmp/chaosengine-pod-cpu-hog-exec.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: pod-cpu-hog-exec
              labels:
                instance_id: 17e5adb4-ad96-438f-be1c-afbc875ab87e
                context: pod-cpu-hog-exec_sj
                workflow_name: pod-cpu-hog-exec-28a-1650197201
            spec:
              engineState: active
              appinfo:
                appns: sj
                applabel: app=nginx
                appkind: deployment
              chaosServiceAccount: litmus-admin
              experiments:
                - name: pod-cpu-hog-exec
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "60"
                        - name: CPU_CORES
                          value: "4"
                        - name: PODS_AFFECTED_PERC
                          value: ""
                    probe: []
              annotationCheck: "false"
    metadata:
      labels:
        weight: "10"
    name: pod-cpu-hog-exec
    outputs: {}
status:
  finishedAt: null
  startedAt: null
