apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 368f38bc-70ed-4ddc-9811-ab4f5c6589eb
    subject: custom-chaos-scenario_litmus
    workflow_id: 8f588f78-2818-4e70-91e6-22aa25aef8e9
    workflows.argoproj.io/controller-instanceid: 368f38bc-70ed-4ddc-9811-ab4f5c6589eb
  name: custom-chaos-scenario-1657797340
  namespace: litmus
spec:
  concurrencyPolicy: Forbid
  schedule: 45 16 * * 0-6
  startingDeadlineSeconds: 0
  timezone: Asia/Calcutta
  workflowMetadata:
    creationTimestamp: null
    labels:
      cluster_id: 368f38bc-70ed-4ddc-9811-ab4f5c6589eb
      workflow_id: 8f588f78-2818-4e70-91e6-22aa25aef8e9
      workflows.argoproj.io/controller-instanceid: 368f38bc-70ed-4ddc-9811-ab4f5c6589eb
  workflowSpec:
    arguments:
      parameters:
      - name: adminModeNamespace
        value: litmus
    entrypoint: custom-chaos
    podGC:
      strategy: OnWorkflowCompletion
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccountName: argo-chaos
    templates:
    - inputs: {}
      metadata: {}
      name: custom-chaos
      outputs: {}
      steps:
      - - arguments: {}
          name: install-chaos-experiments
          template: install-chaos-experiments
      - - arguments: {}
          name: pod-delete-ebd
          template: pod-delete-ebd
      - - arguments: {}
          name: revert-chaos
          template: revert-chaos
    - container:
        args:
        - kubectl apply -f /tmp/pod-delete-ebd.yaml -n {{workflow.parameters.adminModeNamespace}}
          |  sleep 30
        command:
        - sh
        - -c
        image: litmuschaos/k8s:2.10.0
        name: ""
        resources: {}
      inputs:
        artifacts:
        - name: pod-delete-ebd
          path: /tmp/pod-delete-ebd.yaml
          raw:
            data: |
              apiVersion: litmuschaos.io/v1alpha1
              description:
                message: |
                  Deletes a pod belonging to a deployment/statefulset/daemonset
              kind: ChaosExperiment
              metadata:
                name: pod-delete
                labels:
                  name: pod-delete
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: chaosexperiment
                  app.kubernetes.io/version: 2.10.0
              spec:
                definition:
                  scope: Namespaced
                  permissions:
                    - apiGroups:
                        - ""
                      resources:
                        - pods
                      verbs:
                        - create
                        - delete
                        - get
                        - list
                        - patch
                        - update
                        - deletecollection
                    - apiGroups:
                        - ""
                      resources:
                        - events
                      verbs:
                        - create
                        - get
                        - list
                        - patch
                        - update
                    - apiGroups:
                        - ""
                      resources:
                        - configmaps
                      verbs:
                        - get
                        - list
                    - apiGroups:
                        - ""
                      resources:
                        - pods/log
                      verbs:
                        - get
                        - list
                        - watch
                    - apiGroups:
                        - ""
                      resources:
                        - pods/exec
                      verbs:
                        - get
                        - list
                        - create
                    - apiGroups:
                        - apps
                      resources:
                        - deployments
                        - statefulsets
                        - replicasets
                        - daemonsets
                      verbs:
                        - list
                        - get
                    - apiGroups:
                        - apps.openshift.io
                      resources:
                        - deploymentconfigs
                      verbs:
                        - list
                        - get
                    - apiGroups:
                        - ""
                      resources:
                        - replicationcontrollers
                      verbs:
                        - get
                        - list
                    - apiGroups:
                        - argoproj.io
                      resources:
                        - rollouts
                      verbs:
                        - list
                        - get
                    - apiGroups:
                        - batch
                      resources:
                        - jobs
                      verbs:
                        - create
                        - list
                        - get
                        - delete
                        - deletecollection
                    - apiGroups:
                        - litmuschaos.io
                      resources:
                        - chaosengines
                        - chaosexperiments
                        - chaosresults
                      verbs:
                        - create
                        - list
                        - get
                        - patch
                        - update
                        - delete
                  image: litmuschaos/go-runner:2.10.0
                  imagePullPolicy: Always
                  args:
                    - -c
                    - ./experiments -name pod-delete
                  command:
                    - /bin/bash
                  env:
                    - name: TOTAL_CHAOS_DURATION
                      value: "15"
                    - name: RAMP_TIME
                      value: ""
                    - name: FORCE
                      value: "true"
                    - name: CHAOS_INTERVAL
                      value: "5"
                    - name: PODS_AFFECTED_PERC
                      value: ""
                    - name: LIB
                      value: litmus
                    - name: TARGET_PODS
                      value: ""
                    - name: NODE_LABEL
                      value: ""
                    - name: SEQUENCE
                      value: parallel
                  labels:
                    name: pod-delete
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: experiment-job
                    app.kubernetes.io/version: 2.10.0
      metadata: {}
      name: install-chaos-experiments
      outputs: {}
    - container:
        args:
        - -file=/tmp/chaosengine-pod-delete-ebd.yaml
        - -saveName=/tmp/engine-name
        image: litmuschaos/litmus-checker:2.10.0
        name: ""
        resources: {}
      inputs:
        artifacts:
        - name: pod-delete-ebd
          path: /tmp/chaosengine-pod-delete-ebd.yaml
          raw:
            data: |
              apiVersion: litmuschaos.io/v1alpha1
              kind: ChaosEngine
              metadata:
                namespace: "{{workflow.parameters.adminModeNamespace}}"
                generateName: pod-delete-ebd
                labels:
                  instance_id: d93b1e60-d10c-448e-9c76-3bdd202193fb
                  workflow_name: custom-chaos-scenario-1657797340
              spec:
                appinfo:
                  appns: default
                  applabel: app=nginx
                  appkind: deployment
                engineState: active
                chaosServiceAccount: litmus-admin
                experiments:
                  - name: pod-delete
                    spec:
                      components:
                        env:
                          - name: TOTAL_CHAOS_DURATION
                            value: "30"
                          - name: CHAOS_INTERVAL
                            value: "10"
                          - name: FORCE
                            value: "false"
                          - name: PODS_AFFECTED_PERC
                            value: ""
      metadata:
        labels:
          weight: "10"
      name: pod-delete-ebd
      outputs: {}
    - container:
        args:
        - 'kubectl delete chaosengine -l ''instance_id in (d93b1e60-d10c-448e-9c76-3bdd202193fb,
          )'' -n {{workflow.parameters.adminModeNamespace}} '
        command:
        - sh
        - -c
        image: litmuschaos/k8s:2.10.0
        name: ""
        resources: {}
      inputs: {}
      metadata: {}
      name: revert-chaos
      outputs: {}
status:
  active: null
  conditions: null
  lastScheduledTime: null
