apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: bbf6138f-d00b-4b86-95be-77e75ef30de3
    subject: custom-gitops_litmusctl-1
    workflow_id: da1e91d7-2fc4-445d-abb0-99d0aaa848c0
    workflows.argoproj.io/controller-instanceid: bbf6138f-d00b-4b86-95be-77e75ef30de3
  name: custom-gitops-1660292834
  namespace: litmusctl-1
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmusctl-1
  entrypoint: custom-chaos
  imagePullSecrets:
  - name: regcred
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: pod-delete-hw7
        template: pod-delete-hw7
    - - arguments: {}
        name: revert-chaos
        template: revert-chaos
  - container:
      args:
      - kubectl apply -f /tmp/pod-delete-hw7.yaml -n {{workflow.parameters.adminModeNamespace}}
        &&  sleep 30
      command:
      - sh
      - -c
      image: docker.io/chaosnative/k8s:2.11.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-delete-hw7
        path: /tmp/pod-delete-hw7.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Deletes a pod belonging to a deployment/statefulset/daemonset
            kind: ChaosExperiment
            metadata:
              name: pod-delete
              version: 0.1.19
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                      - apps
                      - batch
                      - litmuschaos.io
                    resources:
                      - deployments
                      - jobs
                      - pods
                      - pods/log
                      - events
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                      - deletecollection
                image: litmuschaos/go-runner:latest
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name pod-delete
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "15"
                  - name: RAMP_TIME
                    value: ""
                  - name: FORCE
                    value: "true"
                  - name: CHAOS_INTERVAL
                    value: "5"
                  - name: PODS_AFFECTED_PERC
                    value: ""
                  - name: LIB
                    value: litmus
                  - name: TARGET_POD
                    value: ""
                  - name: SEQUENCE
                    value: parallel
                labels:
                  name: pod-delete
                  app.kubernetes.io/part-of: litmus
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-pod-delete-hw7.yaml
      - -saveName=/tmp/engine-name
      image: docker.io/chaosnative/litmus-checker:2.11.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-delete-hw7
        path: /tmp/chaosengine-pod-delete-hw7.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: pod-delete-hw7
              labels:
                instance_id: d717899a-f735-4cff-9356-c6091c0153e2
            spec:
              appinfo:
                appns: default
                applabel: app=nginx
                appkind: deployment
              annotationCheck: "true"
              engineState: active
              auxiliaryAppInfo: ""
              chaosServiceAccount: litmus-admin
              monitoring: false
              jobCleanUpPolicy: retain
              experiments:
                - name: pod-delete
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "30"
                        - name: CHAOS_INTERVAL
                          value: "10"
                        - name: FORCE
                          value: "false"
                      experimentImagePullSecrets:
                        - name: regcred
              components:
                runner:
                  imagePullSecrets:
                    - name: regcred
    metadata:
      labels:
        weight: "10"
    name: pod-delete-hw7
    outputs: {}
  - container:
      args:
      - 'kubectl delete chaosengine -l ''instance_id in (d717899a-f735-4cff-9356-c6091c0153e2,
        )'' -n {{workflow.parameters.adminModeNamespace}} '
      command:
      - sh
      - -c
      image: docker.io/chaosnative/k8s:2.11.0
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: revert-chaos
    outputs: {}
status:
  finishedAt: null
  startedAt: null
