apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 80de7161-afc7-4df8-9855-dbd6ce8d95b5
    subject: bank-of-anthos_litmus
    workflow_id: b497c392-819e-4e42-9c7b-ed3aa7f2f030
    workflows.argoproj.io/controller-instanceid: 80de7161-afc7-4df8-9855-dbd6ce8d95b5
  name: bank-of-anthos-1647265737
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
    - name: appNamespace
      value: bank
  entrypoint: argowf-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: argowf-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-application
        template: install-application
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: pod-network-loss
        template: pod-network-loss
    - - arguments: {}
        name: revert-chaos
        template: revert-chaos
      - arguments: {}
        name: delete-application
        template: delete-application
  - container:
      args:
      - -namespace=bank
      - -typeName=weak
      - -operation=apply
      - -timeout=400
      - -app=bank-of-anthos
      - -scope=cluster
      image: litmuschaos/litmus-app-deployer:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: install-application
    outputs: {}
  - container:
      args:
      - kubectl apply -f https://hub.litmuschaos.io/api/chaos/2.6.0?file=charts/generic/experiments.yaml
        -n {{workflow.parameters.adminModeNamespace}} ; sleep 30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-network-loss
        path: /tmp/chaosengine.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              labels:
                instance_id: 824d5b5b-cc65-4e72-a169-f8b3795e8e81
                workflow_name: bank-of-anthos-1647265737
              generateName: pod-network-loss-chaos
            spec:
              appinfo:
                appns: bank
                applabel: name in (balancereader,transactionhistory)
                appkind: deployment
              jobCleanUpPolicy: retain
              engineState: active
              chaosServiceAccount: litmus-admin
              components:
                runner:
                  imagePullPolicy: Always
              experiments:
                - name: pod-network-loss
                  spec:
                    probe:
                      - name: check-frontend-access-url
                        type: httpProbe
                        httpProbe/inputs:
                          url: http://frontend.bank.svc.cluster.local:80
                          responseTimeout: 100
                          method:
                            get:
                              criteria: ==
                              responseCode: "200"
                        mode: Continuous
                        runProperties:
                          probeTimeout: 2
                          interval: 1
                          retry: 2
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "90"
                        - name: NETWORK_INTERFACE
                          value: eth0
                        - name: NETWORK_PACKET_LOSS_PERCENTAGE
                          value: "100"
                        - name: CONTAINER_RUNTIME
                          value: docker
                        - name: SOCKET_PATH
                          value: /var/run/docker.sock
    metadata:
      labels:
        weight: "10"
    name: pod-network-loss
    outputs: {}
  - container:
      args:
      - -namespace=bank
      - -typeName=resilient
      - -operation=delete
      - -app=bank-of-anthos
      image: litmuschaos/litmus-app-deployer:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: delete-application
    outputs: {}
  - container:
      args:
      - 'kubectl delete chaosengine -l ''instance_id in (824d5b5b-cc65-4e72-a169-f8b3795e8e81,
        )'' -n {{workflow.parameters.adminModeNamespace}} '
      command:
      - sh
      - -c
      image: litmuschaos/k8s:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: revert-chaos
    outputs: {}
status:
  finishedAt: null
  startedAt: null
